export const mockData = {
  user: {
    fighter: {
      userId: "fighter_001",
      fullName: "Alex Nguyen",
      nickname: "The Hammer",
      weightClass: "145 lbs",
      discipline: "MMA",
      avatarUrl: "https://example.com/mock/avatar_alex.png",
      sparSampleVideoUrl: "https://example.com/mock/spar_alex.mp4",
      elo: 1325,
      tier: "Silver",
    },
    coach: {
      userId: "coach_001",
      gymName: "Dragon Fury MMA",
      address: "123 Fight St, Ho Chi Minh City, Vietnam",
      disciplines: ["MMA", "Muay Thai", "BJJ"],
      logoUrl: "https://example.com/mock/logo_dragonfury.png",
      gymVerified: true,
      documents: ["https://example.com/docs/license_dragonfury.pdf", "https://example.com/docs/id_maria.png"],
    },
    fan: {
      userId: "fan_001",
      fullName: "Jordan Lee",
      avatarUrl: "https://example.com/mock/avatar_jordan.png",
      interests: ["Boxing", "MMA"],
    },
  },
  feed: [
    {
      type: "video",
      videoUrl: "https://example.com/mock/spar_alexhighlight.mp4",
      fighterName: "Alex Nguyen",
      elo: 1325,
      tier: "Silver",
      stats: { power: 68, defense: 54, accuracy: 72 },
      description: "Alex's top combo from yesterday's spar.",
      likes: 248,
      comments: 16,
    },
    {
      type: "event",
      eventId: "event_001",
      title: "Saturday Night Boxing Showdown",
      date: "2025-07-12",
      time: "19:00",
      location: "Dragon Fury MMA Arena",
      price: 25.0,
      tiers: ["General Admission", "VIP Ringside"],
      bannerImageUrl: "https://example.com/mock/event_banner_boxing.png",
    },
    {
      type: "video",
      videoUrl: "https://example.com/mock/spar_maria.mp4",
      fighterName: 'Maria "The Dragon" Lopez',
      elo: 1580,
      tier: "Gold",
      stats: { power: 82, defense: 61, accuracy: 78 },
      description: "Maria's defensive masterclass.",
      likes: 512,
      comments: 42,
    },
    {
      type: "announcement",
      text: "Coach Luis hosting a free boxing pad-work workshop on 2025-07-07. RSVP now!",
      datePosted: "2025-06-30",
    },
  ],
  fighters: [
    {
      fighterId: "fighter_002",
      name: "Carlos Santos",
      nickname: "El Toro",
      avatarUrl: "https://example.com/mock/avatar_carlos.png",
      elo: 1420,
      tier: "Silver",
      weightClass: "145 lbs",
      discipline: "Muay Thai",
      distance: "3 km",
      lastSeen: "2 hrs ago",
      profileVideoUrl: "https://example.com/mock/spar_carlos.mp4",
    },
    {
      fighterId: "fighter_003",
      name: "Linh Tran",
      nickname: "White Tiger",
      avatarUrl: "https://example.com/mock/avatar_linh.png",
      elo: 1580,
      tier: "Gold",
      weightClass: "135 lbs",
      discipline: "Boxing",
      distance: "5 km",
      lastSeen: "30 min ago",
      profileVideoUrl: "https://example.com/mock/spar_linh.mp4",
    },
    {
      fighterId: "fighter_004",
      name: 'Michael "Big Mike" Jones',
      nickname: "Big Mike",
      avatarUrl: "https://example.com/mock/avatar_mike.png",
      elo: 1250,
      tier: "Bronze",
      weightClass: "155 lbs",
      discipline: "MMA",
      distance: "9 km",
      lastSeen: "1 day ago",
      profileVideoUrl: "https://example.com/mock/spar_mike.mp4",
    },
  ],
  events: [
    {
      eventId: "event_002",
      title: "Wednesday Night Spar Drop-In",
      date: "2025-07-02",
      time: "18:00",
      location: "Dragon Fury MMA Gym",
      price: 0.0,
      isFree: true,
      spotsAvailable: 8,
      bannerImageUrl: "https://example.com/mock/event_spardropin.png",
    },
    {
      eventId: "event_003",
      title: "Pro MMA Fight Card: Titans Clash",
      date: "2025-07-10",
      time: "20:00",
      location: "HCMC Sports Arena",
      price: 35.0,
      isFree: false,
      tiers: [
        { name: "General Admission", price: 35.0 },
        { name: "VIP Ringside", price: 80.0 },
      ],
      bannerImageUrl: "https://example.com/mock/event_titansclash.png",
    },
    {
      eventId: "event_004",
      title: "Amateur Boxing Tournament—Qualifier",
      date: "2025-07-15",
      time: "17:00",
      location: "Saigon Sports Center",
      price: 10.0,
      isFree: false,
      tiers: [{ name: "General Admission", price: 10.0 }],
      bannerImageUrl: "https://example.com/mock/event_boxingqualifier.png",
    },
  ],
  sessions: [
    {
      sessionId: "session_001",
      date: "2025-06-18",
      videoUrl: "https://example.com/mock/spar_alex06018.mp4",
      metrics: { power: 65, defense: 50, accuracy: 70 },
      eloAfter: 1325,
    },
    {
      sessionId: "session_002",
      date: "2025-06-25",
      videoUrl: "https://example.com/mock/spar_alex0625.mp4",
      metrics: { power: 68, defense: 54, accuracy: 72 },
      eloAfter: 1340,
    },
  ],
  sparInvites: [
    {
      inviteId: "invite_001",
      fromFighter: "Linh Tran",
      elo: 1580,
      tier: "Gold",
      message: "Hey Alex, want to spar tomorrow at 6 PM?",
      sentAt: "2 hrs ago",
    },
  ],
  roster: [
    { fighterId: "fighter_002", name: "Carlos Santos", elo: 1420, tier: "Silver" },
    { fighterId: "fighter_003", name: "Linh Tran", elo: 1580, tier: "Gold" },
  ],
  followedFighters: [
    {
      fighterId: "fighter_002",
      name: "Carlos Santos",
      avatarUrl: "https://example.com/mock/avatar_carlos.png",
      tier: "Silver",
    },
    {
      fighterId: "fighter_003",
      name: "Linh Tran",
      avatarUrl: "https://example.com/mock/avatar_linh.png",
      tier: "Gold",
    },
  ],
}
